name: EconomyPluginRM
version: '${project.version}'
main: zartox.economypluginrm.EconomyPluginRM
api-version: '1.20'
authors: [Zartox]
commands:
  savelogs:
    description: Save the logs of the EconomyPluginRM manually.
    usage: /savelogs
  destroy:
    description: Destroy someone's shop or private chest
    usage: /destroy
  listchest:
    description: List all the private chests
    usage: /listchest
  suicide:
    description: kind of explains itself...
    usage: /suicide